python train.py \
  -b 1 \
  -e 20 \
  -l 0.0005 \
  -r 100 \
  -n 'test_Varnet' \
  -t '/home/Data/train/' \
  -v '/home/Data/val/' \
  --cascade 11 \
  --chans 18 \
  --sens_chans 8 \
  --seed 91 \
  --start 3 # start augmentation from (n+2)th epoch (b/c epoch starts from 0, no augmentation until '--start')